# Generated by Django 5.1.4 on 2024-12-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customsuser",
            name="tg_chat_id",
            field=models.CharField(
                blank=True, null=True, verbose_name="ID чата в Telegram"
            ),
        ),
    ]
