# Generated by Django 5.1.4 on 2025-01-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        help_text="Укажите место, в котором необходимо выполнять привычку",
                        max_length=150,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Укажите время, когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Укажите действие, которое представляет собой привычка",
                        max_length=150,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("every minutes", "каждую минуту"),
                            ("every hour", "каждый час"),
                            ("every day", "каждый день"),
                            ("every other day", "через день"),
                            ("every three days", "раз в 3 дня"),
                            ("every four days", "раз в 4 дня"),
                            ("every five days", "раз в 5 дней"),
                            ("every six days", "раз в 6 дней"),
                            ("every week", "раз в неделю"),
                        ],
                        default="every day",
                        help_text="Выберите периодичность выполнения привычки",
                        max_length=16,
                        verbose_name="Периодичность выполнения",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Укажите вознаграждение",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.IntegerField(
                        default=1,
                        help_text="Укажите предположительное время выполнения привычки в минутах",
                        verbose_name="Время выполнения",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать привычку для общего доступа",
                        verbose_name="Общий доступ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["action"],
            },
        ),
    ]
