# Generated by Django 5.1.4 on 2024-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("every minutes", "каждую минуту"),
                    ("every hour", "каждый час"),
                    ("every day", "каждый день"),
                    ("every other day", "через день"),
                    ("every three days", "раз в 3 дня"),
                    ("every four days", "раз в 4 дня"),
                    ("every five days", "раз в 5 дней"),
                    ("every six days", "раз в 6 дней"),
                    ("every week", "раз в неделю"),
                ],
                default="every day",
                help_text="Выберите периодичность выполнения привычки",
                max_length=16,
                verbose_name="Периодичность выполнения",
            ),
        ),
    ]
